### ISSUE TITLE
Missing word

### ISSUE THREAD

**Issue by james2432** [henrymyers/lorembarnak#10]
Would you consider adding "fucking" to the list of words?

i.e.

`ostid fucking crisse de tabarnak`

it rolls off the tongue in pop QC joual or are you being a purist so L'Office de la langue française won't come and arrest you?

**Comment by henrymyers** [comment]
I think we should leave Americans the one swear they have 😉 

While I do think it's fun to say, I'll admit I'm kind of leaning towards keeping it french-exclusive.
