### ISSUE TITLE
New words, and recategorization of some words

### ISSUE THREAD

**Issue by Souliest** [henrymyers/lorembarnak#13]
Hi!
I love the project! It's only an opinion, but some words already in there belong in the same family.
_torvisse_ -> _torrieux_
_charogne_ -> _charrue_

Also, some new ones that I've heard over the years, along with the families they belong to. You're welcome to add any or all!
_torvinouche_ -> _torrieux_
_calvinouche_ -> _calvaire_
_bout d'cierge_ -> _bout d'crisse_
_batèche_ -> _baptême_
_géritole_ -> _gériboire_
_crucifix_ -> _crisse_
_'ti jésus_ -> _jésus de plâtre_
_cochonnerie_ -> _patente à gosse_
_cossin_ -> _patente à gosse_

Anyway, keep it up! It certainly brought a smile to my face this morning!

**Comment by henrymyers** [comment]
Thank you so much! I was actually getting ready to add a few swears that have come in over the past few days, and **all of yours** are new and great. 🥇 

I'll make all the changes you suggested

**Comment by montplaisir** [comment]
torpinouche, tabarnane, tabaslack

très rigolo merci

**Comment by henrymyers** [comment]
Added ✅  Thanks for the suggestions!
