### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by lbech067** [henrymyers/lorembarnak#14]
Few suggestions you might enjoy adding :

Perfide pigeon
Anus de poulpe
Balai de chiotte
Betterave molle
Bougre d'âne
Cher vieux débris
Voyou
Cloaque incapable
Gredin miteux
Renégat
Scélérate suintance
Microcéphale marécageux
Mécréant insipide

Sapristi de saucisse
Saperlipopette
Diantre Diane
Purée

**Comment by henrymyers** [comment]
While extremely fun to say, most of the expressions above aren't really traditional Québécois swears.

`purée` is pure gold though 🏅 Added
