### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AkironQc** [henrymyers/lorembarnak#25]
J'ai recemment commencé a utiliser Visual Studio Code dans mon cours de programmation Web et j'aimerais bien qu'il existe un extension pour utiliser LoremBarnack au lieux du LoremIpsum classic. Ça serait drole et déja mieux que le LoremIpsum ^^

**Comment by AkironQc** [comment]
Aussi une expression a ajouté je crois pas qu'il est vraiment commun mais ma grand mère l'utilisait beaucoup: Sac à papier de Gozwell

Bon Sacrage!!!

**Comment by hecht-a** [comment]
Hey @AkironQc, j'ai apprécié l'idée. C'est pourquoi j'ai fait cette extension.
Voilà le repo github de l'extension si vous avez des suggestions: https://github.com/hecht-a/vscode-lorem-barnak
Et voilà le lien de téléchargement: https://marketplace.visualstudio.com/items?itemName=HECHTAxel.lorem-barnak

En espérant que cela vous plaise. :)

**Comment by henrymyers** [comment]
@hecht-a Génial! Tu peux créer une PR pour ajouter un lien vers ton extension dans le readme si tu veux :D
